### PR TITLE
Publish Asciidoclet v2.0.0 docs

### PR DESCRIPTION
**Pull request by abelsromero**

### CODE REVIEW

**Comment by abelsromero** [comment]
Done! https://github.com/asciidoctor/asciidoclet/pull/139.
For validation, I could see the error locally and now it's not showing, but I cannot re-run Netlify pipeline.

**Comment by mojavelinux** [comment]
If you force push to this branch, it will cause the Netlify build to run again. Use `git commit --amend --date="$(date)"` to remake the commit.

**Comment by abelsromero** [comment]
All seems fine now

**Comment by mojavelinux** [comment]
Excellent! Let's go for it.

**Pull request merged**
