### PR TITLE
Add maven-plugin docs

### PR DESCRIPTION
**Pull request by abelsromero**
**As soon as the branch is merged in the maven-plugin repo** this could be too.
I understand no more changes are required here.

One question I have though, is how will this be made accessible. Menu in the ui?

### CODE REVIEW

**Comment by Mogztter** [comment]
@abelsromero I think you should configure your fork/branch so everyone can take a look with Netlify deploy preview. What do you think?

**Comment by abelsromero** [comment]
As a quick win I made it so the docs are also published as GH-PAGES https://asciidoctor.github.io/asciidoctor-maven-plugin/maven-plugin/2.1/.

**Comment by mojavelinux** [comment]
> As a quick win I made it so the docs are also published as GH-PAGES

Keep in mind that when you submit a PR to this repository, you already get a deploy preview.

**Comment by mojavelinux** [comment]
> how will this be made accessible.

It shows up in the component explore drawer. I'm also going to add links in the top nav to the default page for each project's documentation (since the component explore drawer isn't intuitive to all and not very prominent).

**Comment by mojavelinux** [comment]
Is this ready to merge?

Quick tip. If you rename the doctitle of the start page to "Asciidoctor Maven Tools Documentation", then the page will show up as "Introduction" in the breadcrumbs. (See https://github.com/asciidoctor/asciidoctor-docs-ui/blob/main/src/partials/breadcrumbs.hbs#L11). I also recommend setting the `navtitle` document attribute for that page to that value because eventually we will use the value of that attribute instead.

**Comment by abelsromero** [comment]
> I also recommend setting the `navtitle` document attribute for that page to that value because eventually we will use the value of that attribute instead.

You mean `:navtitle: Introduction` right?

**Comment by mojavelinux** [comment]
You got it! (In the future, this will allow you to control it if for some reason you want to change it).

Note that I still need to update the UI to make use of it, but that depends on it being there in the first place ;)

**Comment by abelsromero** [comment]
https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/501/

**Comment by mojavelinux** [comment]
@abelsromero Are you ready for this to be merged?

**Comment by mojavelinux** [comment]
Since the title is "Maven Tools", should we change the component name to maven-tools? cc: @Mogztter @abelsromero

**Comment by abelsromero** [comment]
> Since the title is "Maven Tools", should we change the component name to maven-tools? cc: @Mogztter @abelsromero

It make sense, if it makes sense in terms of generated urls I can change it in no time.

**Comment by abelsromero** [comment]
To confirm, all is ready 👍

**Comment by mojavelinux** [comment]
Fantastic. Let's go!

**Comment by mojavelinux** [comment]
Maven Tools are in! https://asciidoctor-docs.netlify.app/maven-tools/latest/

**Pull request merged**
