### PR TITLE
Add the Asciidoctor.js CLI documentation

### PR DESCRIPTION
**Pull request by Mogztter**

### CODE REVIEW

**Comment by mojavelinux** [comment]
Did you still want to add this? If so, can you submit a new PR. When I deleted the master branch, GitHub killed the PR.

**Comment by mojavelinux** [comment]
Aha! I saved it ;)

**Comment by Mogztter** [comment]
> Did you still want to add this?

Yes :100:

**Comment by Mogztter** [comment]
cli

:tada: :tada: :tada:

**Pull request merged**
