### PR TITLE
Add Gradle Plugin docs

### PR DESCRIPTION
**Pull request by abelsromero**
~This is for preview from the forked branch linked to PR https://github.com/asciidoctor/asciidoctor-gradle-plugin/pull/601~

Updated to new PR https://github.com/asciidoctor/asciidoctor-gradle-plugin/pull/722

### CODE REVIEW

**Comment by abelsromero** [comment]
I don't understand the error. It seems to be looking for a path that does actually not exist.

```
12:49:35 PM:   ✖ FAIL load public/docinfo
12:49:35 PM:   | operator: load
12:49:35 PM:   | expected: 200 public/docinfo
12:49:35 PM:   |   actual: ENOENT: no such file or directory, open '/opt/build/repo/netlify/public/docinfo'
12:49:35 PM:   |       at: public/gradle-plugin/latest/docinfo/index.html:322:17 <a href="https://docs.asciidoctor.org/docinfo">...</a>
12:49:35 PM:   2519 tests
12:49:35 PM:      2 skipped
12:49:35 PM:   2518 passed
12:49:35 PM:      1 failed
12:49:35 PM: ​
```

**Comment by abelsromero** [comment]
Found an invalid referente, fixing :+1:

**Comment by abelsromero** [comment]
I'd need to review the status sorry, I recall the branch structure was not the same as for asciidoctorj/maven and I found some problem.

**Comment by mojavelinux** [comment]
No worries. I just wanted to make sure you weren't waiting on me. I'll be ready when you are ;)

**Comment by abelsromero** [comment]
I need to re-think this.

**Comment by abelsromero** [comment]
Running to get preview, when all is fine I'll open PR pointing to the branch in the official gradle repo, not my fork.
@mojavelinux this is running fine locally without errors but you always spot some extra fixes. Is there anything else I should be checking other than the netifly preview.

**Comment by mojavelinux** [comment]
If it builds clean and the docs show up, I think that's sufficient, at least to start. We can always make adjustments after it goes live.

**Comment by abelsromero** [comment]
Thanks! Found an issue with a branch name thanks to the validations.
This is the preview :point_right:  https://deploy-preview-66--asciidoctor-docs.netlify.app/ I think it's not perfect but serviceable.

**Comment by mojavelinux** [comment]
This is a great start! Tremendous work. I'm so glad to see these docs finally come home.

I'd like to request a few small changes before we merging.

* Change "Asciidoctorj PDF plugin" title to "AsciidoctorJ PDF plugin" (note the uppercase J)
* Move "Working with Asciidoctor.js instead" to Appendices (this is very much a niche case and seems to belong there for now)
* Group plugins under a "Plugins" nav entry (doesn't have to be a page)
* I don't think the "Introduction" nav entry is needed as this just duplicates the start page, so it just makes it seem like the navigation is not working correctly

Does that sound reasonable?

**Comment by abelsromero** [comment]
> https://github.com/asciidoctor/docs.asciidoctor.org/pull/66#issuecomment-1987900487

Sure thing! When migrating I am so focused on the technical details (attributes, includes, refs, etc.) that I lose sight of keeping cohesion and user experience.

**Comment by mojavelinux** [comment]
Should we put asciidoctoreditorconfig-plugin.adoc under plugins too?

Aside from that, I think we can call it done for the first go live.

**Comment by mojavelinux** [comment]
Looks great! Super work!

Let's go! :rocket:

**Pull request merged**
