### PR TITLE
add asciidoctor-epub3 documentation

### PR DESCRIPTION
**Pull request by slonopotamus**
Accompanying PR: https://github.com/asciidoctor/asciidoctor-epub3/pull/391

### CODE REVIEW

**Comment by mojavelinux** [comment]
If you want to see a deploy preview, you'll need to change the git reference to point to the PR branch until it is merged into the master branch.

**Comment by slonopotamus** [comment]
I tried making a preview from my PR branch and it looks OK: https://deploy-preview-60--asciidoctor-docs.netlify.app/epub3-converter/latest/
Do you want me to adjust EPUB3 position in left-hand component list? I see that you have some [custom order](https://github.com/asciidoctor/docs.asciidoctor.org/blob/main/antora-playbook.yml#L47), however fail to infer the logic behind it.

**Comment by slonopotamus** [comment]
Note to myself: after this gets merged I also need to open a PR to uncomment https://github.com/asciidoctor/asciidoctor-docs-ui/blob/fa9c28ad6c1a6d3612e42b0162fccdb49419c2e2/src/partials/header-content.hbs#L51

**Comment by slonopotamus** [comment]
I switched this PR back to asciidoctor-epub3 main branch, so this can be merged as soon as asciidoctor/asciidoctor-epub3#391 is merged.

**Comment by mojavelinux** [comment]
> Do you want me to adjust EPUB3 position in left-hand component list?

Yes, please list it in the comma separated list after reveal.js-converter.

> however fail to infer the logic behind it.

The `*` represents all components not otherwise listed in alphabetical order. Aside from that, it's just a regular comma-separated list.

**Comment by mojavelinux** [comment]
> I mean, I didn't get the logic behind the exact manual order of components.

Ahhh. Sorry to have misunderstood you.

I don't think there's a perfect order and it may need refinement. I'm roughly trying to list them in the order someone might need to use them, with the core processors up top and the extensions at the bottom. The converters should be grouped, and there order is based on the number of downloads (a rough sense of popularity). Asciidoclet is near the Maven Tools since it is often used together in the same build.

**Comment by slonopotamus** [comment]
> order based on the number of downloads

OK, that makes sense.

So... It seems like everything in this PR and asciidoctor/asciidoctor-epub3#391 is good enough, so maybe you could push the buttons in both of them?

**Comment by mojavelinux** [comment]
Sure thing.

**Comment by mojavelinux** [comment]
It's live. See https://docs.asciidoctor.org/epub3-converter/latest/

I've also added it to the config for the search scraper so it will show up in search results.

**Pull request merged**
